### ISSUE TITLE
Landing page with game instructions

### ISSUE THREAD

**Issue by mh120888** [MandoQ10/wordle#1]
As a player, I want to be able to go to a webpage and see the instructions for the game.

Definition of done:
- the game is available on a publicly accessible webpage
- the page includes the name of the game, "Wordle"
- the page includes instructions for the game
- the page indicates the game is "coming soon"

**Comment by MandoQ10** [comment]
Finished and demoed d7396a414308993f2053bd77ebe59e68e4a5d802
